version: '1.0'

stages:
  - Prepare
  - Build
  - Push
  - Deploy

steps:
  main_clone:
    # https://codefresh.io/docs/docs/codefresh-yaml/steps/git-clone/
    title: "Clone repository"
    type: git-clone
    stage: Prepare
    description: "Clone repository"
    repo: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
    git: github
    revision: ${{CF_REVISION}}

  show_context:
    title: "Show context"
    stage: Prepare
    image: alpine
    commands:
      - |-
        echo "Repo owner: $CF_REPO_OWNER"
        echo "Repo name: $CF_REPO_NAME"
        echo "Branch: $CF_BRANCH"
        echo "Release tag: $CF_RELEASE_TAG"
        echo "Commit URL: $CF_COMMIT_URL"
        echo "Commit message: $CF_COMMIT_MESSAGE"
        echo "Commit author: $CF_COMMIT_AUTHOR"
        echo "Revision: $CF_REVISION"
        echo "Short revision: $CF_SHORT_REVISION"

  build_image:
    title: "Build Docker image"
    stage: Build
    type: build
    description: "Build Docker image"
    image_name: ${{CF_REPO_NAME}}
    tag: ${{CF_SHORT_REVISION}}
    dockerfile: Dockerfile
    no_cache: false
    no_cf_cache: false

  push_image_commit:
    title: "Push image with commit SHA tag"
    stage: Push
    type: push
    candidate: ${{build_image}}
    registry: ecr
    tags:
      - "${{CF_REVISION}}"
      - "${{CF_SHORT_REVISION}}"

  deploy_cicd:
    title: "Deploy to CI/CD cluster"
    stage: Deploy
    image: 'codefresh/cli:latest'
    environment:
      - STAGE=cicd
    commands:
      - codefresh run ${{CF_REPO_NAME}}/deploy -b=${{CF_BRANCH}} -v CF_BRANCH=${{CF_BRANCH}} -v CF_REPO_OWNER=${{CF_REPO_OWNER}} -v CF_REPO_NAME=${{CF_REPO_NAME}} -v CF_REVISION=${{CF_REVISION}} -v CF_SHORT_REVISION=${{CF_SHORT_REVISION}} -v CF_COMMIT_URL=${{CF_COMMIT_URL}} -v "CF_COMMIT_MESSAGE=${{CF_COMMIT_MESSAGE}}" -v CF_COMMIT_AUTHOR=${{CF_COMMIT_AUTHOR}} -v CF_BRANCH_TAG_NORMALIZED=${{CF_BRANCH_TAG_NORMALIZED}} -v CF_BUILD_ID=${{CF_BUILD_ID}} -v STAGE=${STAGE}
    when:
      branch:
        only:
          - main
